version: '3.8'

services:
  mysql:
    image: mysql:8.0
    container_name: swiftcart-mysql
    environment:
      MYSQL_DATABASE: swiftcart
      MYSQL_ROOT_PASSWORD: password
    ports:
      - "3306:3306"
    volumes:
      - mysql-data:/var/lib/mysql

  redis:
    image: redis:7.0-alpine
    container_name: swiftcart-redis
    ports:
      - "6379:6379"
    volumes:
      - redis-data:/data

  backend:
    build: .
    container_name: swiftcartbackend
    ports:
      - "8080:8080"
    depends_on:
      - mysql
      - redis
    environment:
      - DATABASE_URL=jdbc:mysql://swiftcart-mysql:3306/swiftcart?useSSL=false&allowPublicKeyRetrieval=true
      - DATABASE_USER=root
      - DATABASE_PASSWORD=password
      - REDIS_HOST=swiftcart-redis
      - JWT_SECRET=dGhpcy1pcy1hLXN1cGVyLXNlY3JldC1wcm9kdWN0aW9uLWtleS1mb3Itc3dpZnRjYXJ0LWJhY2tlbmQtc2VydmVyLTMyMS1iYXNlNjQ=

volumes:
  mysql-data:
  redis-data:
